package dao;

import db.DatabaseConnection;
import models.Concierge;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for all {@link Concierge}-related database operations
 * in the MIRAGE system.
 *
 * <p>This class is the sole layer responsible for reading from and writing to
 * the {@code concierge} table. Concierge staff are scoped to a single hotel;
 * this association is stored as a foreign key and is respected by the
 * application-level hotel-matching constraint in {@code ExperienceDAO}.</p>
 *
 * <h2>Responsibilities</h2>
 * <ul>
 *   <li>Insert new concierge staff records ({@link #insertConcierge(Concierge)})</li>
 *   <li>Delete a concierge by ID ({@link #deleteConcierge(int)})</li>
 *   <li>Retrieve all concierge staff ({@link #getAllConcierges()})</li>
 *   <li>Retrieve concierge staff filtered by hotel ({@link #getConciergesByHotel(int)})</li>
 * </ul>
 */
public class ConciergeDAO {

    /** Shared database connection obtained from the singleton. */
    private final DatabaseConnection db;

    // ── Constructor ──────────────────────────────────────────────────────────

    /**
     * Constructs a new {@code ConciergeDAO} and acquires the shared database connection.
     *
     * @throws SQLException if the database connection cannot be established
     */
    public ConciergeDAO() throws SQLException {
        this.db = DatabaseConnection.getInstance();
    }

    // ── INSERT ───────────────────────────────────────────────────────────────

    /**
     * Inserts a new concierge record into the {@code concierge} table.
     *
     * <p>The {@code concierge_id} is auto-generated by the database ({@code IDENTITY})
     * and is not written back to the {@code concierge} object by this method.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   INSERT INTO concierge (full_name, hotel_id) VALUES (?, ?)
     * }</pre>
     *
     * @param concierge the {@link Concierge} to persist; must have a non-null
     *                  {@code fullName} and a valid, existing {@code hotelId}
     * @throws SQLException if the hotel ID does not exist (FK violation)
     *                      or a database error occurs
     */
    public void insertConcierge(Concierge concierge) throws SQLException {
        String sql = "INSERT INTO concierge (full_name, hotel_id) VALUES (?,?)";
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        stmt.setString(1, concierge.getFullName());
        stmt.setInt(2, concierge.getHotelId());
        stmt.executeUpdate();
    }

    // ── DELETE ───────────────────────────────────────────────────────────────

    /**
     * Deletes a concierge record from the {@code concierge} table by primary key.
     *
     * <p><b>Warning:</b> If this concierge is referenced by any existing
     * {@code reservation_experience} row, the delete will fail due to a
     * foreign key constraint. The UI should communicate this risk to staff.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   DELETE FROM concierge WHERE concierge_id = ?
     * }</pre>
     *
     * @param conciergeId the ID of the concierge to delete; must be positive
     * @throws SQLException if the concierge is still referenced by experience records
     *                      (FK constraint violation) or a database error occurs
     */
    public void deleteConcierge(int conciergeId) throws SQLException {
        String sql = "DELETE FROM Concierge WHERE concierge_id = ?";
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        stmt.setInt(1, conciergeId);
        stmt.executeUpdate();
    }

    // ── SELECT ───────────────────────────────────────────────────────────────

    /**
     * Retrieves all concierge staff records from the database.
     *
     * <p>Each row is mapped to a {@link Concierge} instance with
     * {@code conciergeId} set via {@link Concierge#setConciergeId(int)}.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   SELECT * FROM concierge
     * }</pre>
     *
     * @return a {@link List} of all {@link Concierge} objects; empty if none exist
     * @throws SQLException if a database error occurs during the query
     */
    public List<Concierge> getAllConcierges() throws SQLException {
        String sql = "SELECT * FROM concierge";
        List<Concierge> concierges = new ArrayList<>();
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        ResultSet result_set = stmt.executeQuery();

        while (result_set.next()) {
            Concierge c = new Concierge(
                    result_set.getString("full_name"),
                    result_set.getInt("hotel_id")
            );
            c.setConciergeId(result_set.getInt("concierge_id"));
            concierges.add(c);
        }
        return concierges;
    }

    /**
     * Retrieves all concierge staff assigned to a specific hotel.
     *
     * <p>Used for filtering the concierge list by hotel when needed.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   SELECT * FROM concierge WHERE hotel_id = ?
     * }</pre>
     *
     * @param hotelId the ID of the hotel to filter by; must be positive
     * @return a {@link List} of {@link Concierge} objects at that hotel;
     *         empty if the hotel has no assigned concierge staff
     * @throws SQLException if a database error occurs during the query
     */
    public List<Concierge> getConciergesByHotel(int hotelId) throws SQLException {
        String sql = "SELECT * FROM concierge WHERE concierge.hotel_id = ?";
        List<Concierge> list = new ArrayList<>();
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        stmt.setInt(1, hotelId);
        ResultSet result_set = stmt.executeQuery();

        while (result_set.next()) {
            Concierge c = new Concierge(
                    result_set.getString("full_name"),
                    result_set.getInt("hotel_id")
            );
            c.setConciergeId(result_set.getInt("concierge_id"));
            list.add(c);
        }
        return list;
    }
}
