package dao;

import db.DatabaseConnection;
import models.Guest;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for all {@link Guest}-related database operations
 * in the MIRAGE system.
 *
 * <p>This class is the sole layer responsible for reading from and writing to
 * the {@code guest} and {@code loyalty_tier_log} tables. All SQL is executed
 * via {@link PreparedStatement} to prevent SQL injection.</p>
 *
 * <p>An instance is obtained by calling the constructor, which acquires the
 * shared {@link DatabaseConnection} singleton. DAOs should be instantiated
 * once per screen controller and reused for the lifetime of that screen.</p>
 *
 * <h2>Responsibilities</h2>
 * <ul>
 *   <li>Insert new guest records ({@link #insertGuest(Guest)})</li>
 *   <li>Update loyalty tier with automatic audit logging
 *       ({@link #updateLoyalityTier(int, String)})</li>
 *   <li>Retrieve all guests ({@link #getAllGuests()})</li>
 *   <li>Increment a guest's cumulative spend ({@link #updateTotalSpend(int, double)})</li>
 * </ul>
 */
public class GuestDAO {

    /** Shared database connection obtained from the singleton. */
    private final DatabaseConnection db;

    // ── Constructor ──────────────────────────────────────────────────────────

    /**
     * Constructs a new {@code GuestDAO} and acquires the shared database connection.
     *
     * @throws SQLException if the database connection cannot be established
     */
    public GuestDAO() throws SQLException {
        this.db = DatabaseConnection.getInstance();
    }

    // ── INSERT ───────────────────────────────────────────────────────────────

    /**
     * Inserts a new guest record into the {@code guest} table.
     *
     * <p>The {@code guest_id} is auto-generated by the database ({@code IDENTITY})
     * and is <em>not</em> written back to the {@code guest} object by this method.
     * The {@code total_spend} column defaults to {@code 0.00} at the database level.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   INSERT INTO guest (full_name, email, phone, loyalty_tier)
     *   VALUES (?, ?, ?, ?)
     * }</pre>
     *
     * @param guest the {@link Guest} to persist; must have non-null
     *              {@code fullName}, {@code email}, and {@code loyaltyTier}
     * @throws SQLException if a database error occurs (e.g. duplicate email,
     *                      constraint violation)
     */
    public void insertGuest(Guest guest) throws SQLException {
        String sql = "INSERT INTO guest (full_name, email, phone, loyalty_tier) VALUES (?,?,?,?)";
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        stmt.setString(1, guest.getFullName());
        stmt.setString(2, guest.getEmail());
        stmt.setString(3, guest.getPhone());
        stmt.setString(4, guest.getLoyaltyTier());
        stmt.executeUpdate();
    }

    // ── UPDATE ───────────────────────────────────────────────────────────────

    /**
     * Updates the loyalty tier of an existing guest and writes an audit log entry
     * to the {@code loyalty_tier_log} table.
     *
     * <p>The operation is performed in three sequential steps:</p>
     * <ol>
     *   <li>Fetch the guest's current tier from the database.</li>
     *   <li>Update the {@code loyalty_tier} column on the {@code guest} row.</li>
     *   <li>Insert a log entry recording the old tier, new tier, and current date.</li>
     * </ol>
     *
     * <p><b>Note:</b> These three steps are executed as individual statements
     * without a wrapping transaction. If the log insert fails after the update
     * succeeds, the audit trail will be incomplete. Consider wrapping in a
     * transaction for production use.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   SELECT loyalty_tier FROM guest WHERE guest_id = ?
     *   UPDATE guest SET loyalty_tier = ? WHERE guest_id = ?
     *   INSERT INTO loyalty_tier_log (guest_id, old_tier, new_tier) VALUES (?, ?, ?)
     * }</pre>
     *
     * @param guestId the ID of the guest whose tier should be updated; must be positive
     * @param newTier the new loyalty tier value; must be one of
     *                {@code "Standard"}, {@code "Silver"}, {@code "Gold"}, {@code "Platinum"}
     * @throws SQLException if the guest ID does not exist or a database error occurs
     */
    public void updateLoyalityTier(int guestId, String newTier) throws SQLException {
        String getTier = "SELECT loyalty_tier FROM guest WHERE guest_id = ?";
        PreparedStatement fetch = db.getConnection().prepareStatement(getTier);
        fetch.setInt(1, guestId);
        ResultSet rs = fetch.executeQuery();
        String oldTier = rs.next() ? rs.getString("loyalty_tier") : "Unknown";

        String update = "UPDATE guest SET loyalty_tier = ? WHERE guest_id = ?";
        PreparedStatement stmt = db.getConnection().prepareStatement(update);
        stmt.setString(1, newTier);
        stmt.setInt(2, guestId);
        stmt.executeUpdate();

        String log = "INSERT INTO loyalty_tier_log (guest_id, old_tier, new_tier) VALUES (?, ?, ?)";
        PreparedStatement logStmt = db.getConnection().prepareStatement(log);
        logStmt.setInt(1, guestId);
        logStmt.setString(2, oldTier);
        logStmt.setString(3, newTier);
        logStmt.executeUpdate();
    }

    /**
     * Increments the cumulative total spend of a guest by the given amount.
     *
     * <p>This is called by {@code CheckoutScreen} after a new experience is
     * successfully added to a reservation folio, to keep the guest's
     * {@code total_spend} column up to date.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   UPDATE guest SET total_spend = total_spend + ? WHERE guest_id = ?
     * }</pre>
     *
     * @param guestId the ID of the guest to update; must be positive and exist in the DB
     * @param amount  the amount to add in USD; must be non-negative
     * @throws SQLException if the guest ID does not exist or a database error occurs
     */
    public void updateTotalSpend(int guestId, double amount) throws SQLException {
        String sql = "UPDATE guest SET total_spend = total_spend + ? WHERE guest_id = ?";
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        stmt.setDouble(1, amount);
        stmt.setInt(2, guestId);
        stmt.executeUpdate();
    }

    // ── SELECT ───────────────────────────────────────────────────────────────

    /**
     * Retrieves all guest records from the database, ordered by insertion sequence.
     *
     * <p>Each row is mapped to a {@link Guest} instance. The {@code guest_id}
     * is set via {@link Guest#setGuestId(int)} after construction.
     * The {@code total_spend} column is <em>not</em> mapped here — only the
     * profile fields relevant to the guest table view are populated.</p>
     *
     * <p><b>SQL executed:</b></p>
     * <pre>{@code
     *   SELECT * FROM guest
     * }</pre>
     *
     * @return a {@link List} of all {@link Guest} objects; empty if no guests exist
     * @throws SQLException if a database error occurs during the query
     */
    public List<Guest> getAllGuests() throws SQLException {
        String sql = "SELECT * FROM guest";
        List<Guest> guests = new ArrayList<>();
        PreparedStatement stmt = db.getConnection().prepareStatement(sql);
        ResultSet result_set = stmt.executeQuery();

        while (result_set.next()) {
            Guest guest = new Guest(
                    result_set.getString("full_name"),
                    result_set.getString("email"),
                    result_set.getString("phone"),
                    result_set.getString("loyalty_tier")
            );
            guest.setGuestId(result_set.getInt("guest_id"));
            guests.add(guest);
        }
        return guests;
    }
}
